/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ChamadoController;
import controller.EquipeController;
import controller.UsuarioController;
import java.util.List;
import model.Atendente;
import model.Categoria;
import model.Chamado;
import model.Classificacao;
import model.Equipe;
import model.Situacao;
import model.Usuario;

/**
 *
 * @author Pichau
 */
public class ChamadoView extends javax.swing.JPanel {
    private Chamado chamado;
    private static final ChamadoController CHAMADO_CONTROLLER = ChamadoController.getInstance();
    private static final UsuarioController USUARIO_CONTROLLER = UsuarioController.getInstance();
    private static final EquipeController EQUIPE_CONTROLLER = EquipeController.getInstance();

    private static ChamadoView instance;

    public static ChamadoView getInstance() {
        if(instance==null){
            instance = new ChamadoView();
        }
        return instance;
    }
    
    
    /**
     * Creates new form ChamadoView
     */
    private ChamadoView() {        
        initComponents();
    }
    
    public void setChamado(Chamado chamado){
        this.chamado = chamado;
        comboCriador.removeAllItems();
        comboCriador.addItem(chamado.getCriador());
        resetComboSolicitante();
        comboSolicitante.setSelectedItem(chamado.getSolicitador());
        resetComboAtendente();
        comboAtendente.setSelectedItem(chamado.getAtendente());
        txtTitulo.setText(chamado.getTitulo());
        txtDescricao.setText(chamado.getDescricao());
        resetComboCassificacao();
        comboClassificacao.setSelectedItem(chamado.getClassificacao());
        comboSituacao.setSelectedItem(chamado.getSituacao());
        txtResolucao.setText(chamado.getResolucao());
        resetComboEquipe();
        comboEquipe.setSelectedItem(chamado.getEquipeResponsavel());
        resetComboCategoria();
        comboCategoria.setSelectedItem(chamado.getCategoria());
        
        System.out.println(chamado.getDataDeCriacao().toLocalDate().toString());
        lblDataCriacao.setText(chamado.getDataDeCriacao().toLocalDate().toString());
        lblDataLimite.setText(chamado.getDataLimite().toLocalDate().toString());
    }
    
    private void resetComboEquipe(){
        ComboEquipe comboReset = (ComboEquipe) comboEquipe;
        comboReset.resetCombo();
        comboEquipe = comboReset;
    }
    
    private void resetComboCategoria(){
        Categoria[] categorias = Categoria.values();
        for (Categoria categoria : categorias) {
            comboCategoria.addItem(categoria);            
        }
    }
    
    private void resetComboCassificacao(){
        Classificacao[] classificacoes = Classificacao.values();
        for (Classificacao classificacao : classificacoes) {
            comboClassificacao.addItem(classificacao);          
        }
    }
    
    private void resetComboSolicitante(){
        List<Usuario> allUsuarios = USUARIO_CONTROLLER.getAllUsuarios();
        comboSolicitante.removeAllItems();
        allUsuarios.forEach((usuario) -> {
            comboSolicitante.addItem(usuario);
        });
    }
    
    private void resetComboAtendente(){
        List<Atendente> allAtendentes = USUARIO_CONTROLLER.getAllAtendentes();
        comboAtendente.removeAllItems();
        allAtendentes.forEach((atendente) -> {
            comboAtendente.addItem(atendente);
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCriador = new javax.swing.JLabel();
        comboCriador = new javax.swing.JComboBox<>();
        lblSolicitante = new javax.swing.JLabel();
        comboSolicitante = new javax.swing.JComboBox<>();
        lolAtendnete = new javax.swing.JLabel();
        comboAtendente = new javax.swing.JComboBox<>();
        lolTitulo = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        lolDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        lolClassificacao = new javax.swing.JLabel();
        comboClassificacao = new javax.swing.JComboBox<>();
        lolSituacao = new javax.swing.JLabel();
        comboSituacao = new view.ComboSituacao();
        lblResolucao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResolucao = new javax.swing.JTextArea();
        lolEquipe = new javax.swing.JLabel();
        comboEquipe = new view.ComboEquipe();
        lblCategoria = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        panelDataCriacao = new javax.swing.JPanel();
        txtDataCriacao = new javax.swing.JLabel();
        lblDataCriacao = new javax.swing.JLabel();
        panelDataLimite = new javax.swing.JPanel();
        txtDataLimite = new javax.swing.JLabel();
        lblDataLimite = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnDeletar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(11, 2));

        lblCriador.setText("Criador");
        jPanel1.add(lblCriador);

        jPanel1.add(comboCriador);

        lblSolicitante.setText("Solicitante");
        jPanel1.add(lblSolicitante);

        jPanel1.add(comboSolicitante);

        lolAtendnete.setText("Atendente");
        jPanel1.add(lolAtendnete);

        comboAtendente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboAtendenteMouseClicked(evt);
            }
        });
        jPanel1.add(comboAtendente);

        lolTitulo.setText("Titulo");
        jPanel1.add(lolTitulo);
        jPanel1.add(txtTitulo);

        lolDescricao.setText("Descricao");
        jPanel1.add(lolDescricao);

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        jPanel1.add(jScrollPane1);

        lolClassificacao.setText("Classificacao");
        jPanel1.add(lolClassificacao);

        jPanel1.add(comboClassificacao);

        lolSituacao.setText("Situacao");
        jPanel1.add(lolSituacao);

        jPanel1.add(comboSituacao);

        lblResolucao.setText("Resolucao");
        jPanel1.add(lblResolucao);

        txtResolucao.setColumns(20);
        txtResolucao.setRows(5);
        jScrollPane2.setViewportView(txtResolucao);

        jPanel1.add(jScrollPane2);

        lolEquipe.setText("Equipe responsável");
        jPanel1.add(lolEquipe);

        jPanel1.add(comboEquipe);

        lblCategoria.setText("Categoria");
        jPanel1.add(lblCategoria);

        jPanel1.add(comboCategoria);

        txtDataCriacao.setText("Data de criação: ");
        panelDataCriacao.add(txtDataCriacao);
        panelDataCriacao.add(lblDataCriacao);

        jPanel1.add(panelDataCriacao);

        txtDataLimite.setText("Data Limite: ");
        panelDataLimite.add(txtDataLimite);
        panelDataLimite.add(lblDataLimite);

        jPanel1.add(panelDataLimite);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        btnDeletar.setText("Excluir");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });
        jPanel2.add(btnDeletar);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalvar);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        chamado.setSolicitador((Usuario) comboSolicitante.getSelectedItem());
        chamado.setAtendente((Atendente) comboAtendente.getSelectedItem());
        chamado.setTitulo(txtTitulo.getText());
        chamado.setDescricao(txtDescricao.getText());
        chamado.setClassificacao((Classificacao) comboClassificacao.getSelectedItem());
        chamado.setSituacao((Situacao) comboSituacao.getSelectedItem());
        chamado.setResolucao(txtResolucao.getText());
        chamado.setEquipeResponsavel((Equipe) comboEquipe.getSelectedItem());
        chamado.setAtendente((Atendente) comboAtendente.getSelectedItem());
        chamado.setCategoria((Categoria) comboCategoria.getSelectedItem());
        
        if (chamado.getSituacao() == Situacao.CONCLUIDO) {
            chamado.getAtendente().resolveChamado();
            chamado.getAtendente().classifica((Classificacao) comboClassificacao.getSelectedItem());
        }
        
        CHAMADO_CONTROLLER.saveChamado(chamado);
        TelaPrincipal.getInstance().showPainel(TelaPrincipal.PAINEL_CHAMADOS);
        TelaPrincipal.getInstance().setInfo("Chamado salvo com sucesso");
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if(chamado.getId() == null){
            TelaPrincipal.getInstance().setInfo("Novo chamado não pode ser excluido");
        }else{
            CHAMADO_CONTROLLER.deleteChamado(chamado);
            TelaPrincipal.getInstance().showPainel(TelaPrincipal.PAINEL_CHAMADOS);
            TelaPrincipal.getInstance().setInfo("Chamado excluido com sucesso");
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void comboAtendenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboAtendenteMouseClicked
    }//GEN-LAST:event_comboAtendenteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Atendente> comboAtendente;
    private javax.swing.JComboBox<Categoria> comboCategoria;
    private javax.swing.JComboBox<Classificacao> comboClassificacao;
    private javax.swing.JComboBox<Usuario> comboCriador;
    private javax.swing.JComboBox<Equipe> comboEquipe;
    private javax.swing.JComboBox<Situacao> comboSituacao;
    private javax.swing.JComboBox<Usuario> comboSolicitante;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblCriador;
    private javax.swing.JLabel lblDataCriacao;
    private javax.swing.JLabel lblDataLimite;
    private javax.swing.JLabel lblResolucao;
    private javax.swing.JLabel lblSolicitante;
    private javax.swing.JLabel lolAtendnete;
    private javax.swing.JLabel lolClassificacao;
    private javax.swing.JLabel lolDescricao;
    private javax.swing.JLabel lolEquipe;
    private javax.swing.JLabel lolSituacao;
    private javax.swing.JLabel lolTitulo;
    private javax.swing.JPanel panelDataCriacao;
    private javax.swing.JPanel panelDataLimite;
    private javax.swing.JLabel txtDataCriacao;
    private javax.swing.JLabel txtDataLimite;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextArea txtResolucao;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
