/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import model.Equipe;

/**
 *
 * @author Pichau
 */
public class EquipesView extends javax.swing.JPanel {
    private static EquipesView instance;

    public static EquipesView getInstance(List<Equipe> equipes) {
        if(instance==null){
            instance = new EquipesView(equipes);
        }
        return instance;
    }
    
    private EquipesTableModel equipesTableModel;

    public EquipesView(List<Equipe> equipes) {
        this.equipesTableModel = new EquipesTableModel(equipes);
        initComponents();
    }
    
    void setEquipes(List<Equipe> equipes){
        EquipesTableModel atualiza = new EquipesTableModel(equipes);
        tableEquipes.setModel(atualiza);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEquipes = new javax.swing.JTable();

        tableEquipes.setModel(this.equipesTableModel);
        tableEquipes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEquipesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEquipes);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void tableEquipesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEquipesMouseClicked
        if(evt.getClickCount()==2){
            int selectedRow = tableEquipes.getSelectedRow();
            EquipesTableModel model = (EquipesTableModel) tableEquipes.getModel();
            Equipe equipeByIndex = model.getEquipeByIndex(selectedRow);
            EquipeView.getInstance().setEquipe(equipeByIndex);
            TelaPrincipal.getInstance().showPainel(TelaPrincipal.PAINEL_EQUIPE);
        }
    }//GEN-LAST:event_tableEquipesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEquipes;
    // End of variables declaration//GEN-END:variables
}
