/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import java.io.UnsupportedEncodingException;
import model.Usuario;

/**
 *
 * @author Pichau
 */
public class LoginView extends javax.swing.JPanel {
    private static LoginView instance;

    public static LoginView getInstance() {
        if(instance==null){
            instance = new LoginView();
        }
        return instance;
    }
    
    private static final UsuarioController USUARIO_CONTROLLER = UsuarioController.getInstance();
    private Usuario usuario;
    
    /**
     * Creates new form Login
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        lblLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblLogin.setText("Bem vindo ao Help Desk, Faça seu login");
        jPanel3.add(lblLogin);

        add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setText("E-mail");
        jPanel1.add(jLabel1);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail);

        jLabel2.setText("Senha");
        jPanel1.add(jLabel2);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginClicked(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnLoginKeyReleased(evt);
            }
        });
        jPanel2.add(btnLogin);

        add(jPanel2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyReleased
    }//GEN-LAST:event_btnLoginKeyReleased

    private void btnLoginClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginClicked
        usuario = USUARIO_CONTROLLER.novoUsuario();
        usuario.setEmail(txtEmail.getText());
        usuario.setSenha(txtPassword.getText());
        try {
            usuario.criptografaSenha();
            usuario = USUARIO_CONTROLLER.login(usuario.getEmail(), usuario.getSenha());
        } catch (UnsupportedEncodingException ex) {
            lblLogin.setText("Não foi possivel verificar o ligin");
        }

        if(usuario == null){
            lblLogin.setText("Usuário ou senha inválidos");
        }else{
            TelaPrincipal telaPrincipal = TelaPrincipal.getInstance();
            telaPrincipal.setUsuarioLogado(usuario);
            telaPrincipal.showPainel(TelaPrincipal.PAINEL_CHAMADOS);
            telaPrincipal.setSize(600, 600);
        }
    }//GEN-LAST:event_btnLoginClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
