/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ChamadoController;
import controller.EquipeController;
import controller.UsuarioController;
import java.awt.CardLayout;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;
import model.Atendente;
import model.Chamado;
import model.Equipe;
import model.Usuario;

/**
 *
 * @author Pichau
 */
public final class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Chamado
     */
    
    private static TelaPrincipal instance;

    public static TelaPrincipal getInstance() {
        if(instance==null){
            instance = new TelaPrincipal();
        }
        return instance;
    }
    
    private Usuario usuarioLogado;
    
    static final String PAINEL_CHAMADO = "PAINEL_CHAMADO";
    static final String PAINEL_CHAMADOS = "PAINEL_CHAMADOS";
    static final String PAINEL_USUARIO = "PAINEL_USUARIO";
    static final String PAINEL_USUARIOS = "PAINEL_USUARIOS";
    static final String PAINEL_EQUIPE = "PAINEL_EQUIPE";
    static final String PAINEL_EQUIPES = "PAINEL_EQUIPES";
    static final String PAINEL_LOGIN = "PAINEL_LOGIN";
    private static final ChamadoController CHAMADO_CONTROLLER = ChamadoController.getInstance();
    private static final UsuarioController USUARIO_CONTROLLER = UsuarioController.getInstance();
    private static final EquipeController EQUIPE_CONTROLLER = EquipeController.getInstance();
    
    private final ChamadoView painelChamado = ChamadoView.getInstance();
    private final List<Chamado> chamados = new ArrayList();
    private final ChamadosView painelChamados = ChamadosView.getInstance(chamados);
    private final UsuarioView painelUsuario = UsuarioView.getInstance();
    private final List<Usuario> usuarios = UsuarioController.getInstance().getAllUsuarios();
    private final UsuariosView painelUsuarios = UsuariosView.getInstance(usuarios);
    private final EquipeView painelEquipe = EquipeView.getInstance();
    private final List<Equipe> equipes = EquipeController.getInstance().getAllEquipe();
    private final EquipesView painelEquipes = EquipesView.getInstance(equipes);
    private final LoginView panelLogin = LoginView.getInstance();
    
    
    private TelaPrincipal() {
        initComponents();
        this.setSize(600, 200);
        this.setLocationRelativeTo(null);
        painelPrincipal.add(PAINEL_CHAMADO, painelChamado);
        painelPrincipal.add(PAINEL_CHAMADOS, painelChamados);
        painelPrincipal.add(PAINEL_USUARIO, painelUsuario);
        painelPrincipal.add(PAINEL_USUARIOS, painelUsuarios);
        painelPrincipal.add(PAINEL_EQUIPE, painelEquipe);
        painelPrincipal.add(PAINEL_EQUIPES, painelEquipes);
        painelPrincipal.add(PAINEL_LOGIN, panelLogin);
        showPainel(PAINEL_LOGIN);
    }

    public Usuario getUsuarioLogado() {
        return usuarioLogado;
    }

    public void setUsuarioLogado(Usuario usuarioLogado) {
        this.usuarioLogado = usuarioLogado;
        menuChamdos.setEnabled(true);
        menuUsuario.setEnabled(true);
        if(usuarioLogado instanceof Atendente){
            menuEquipe.setEnabled(true);
            menuCriarUsuario.setEnabled(true);
            menuCriarAtendente.setEnabled(true);
            menuChamadoSemAtendentes.setEnabled(true);
            menuListarUsuario.setEnabled(true);
            menuChamadoTodos.setEnabled(true);
        }
    }
    
    void showPainel(String panel) {
        CardLayout cl = (CardLayout) painelPrincipal.getLayout();
        cl.show(painelPrincipal, panel);
        setInfo("");
    }
    
    void setInfo(String info){
        lblInfo.setText(info);
    }
    
    void expiraCamado(){
        CHAMADO_CONTROLLER.expiraChamado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInfo = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        painelPrincipal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuChamdos = new javax.swing.JMenu();
        menuCriarChamado = new javax.swing.JMenuItem();
        menuMeusChamados = new javax.swing.JMenuItem();
        menuChamadoSemAtendentes = new javax.swing.JMenuItem();
        menuChamadoTodos = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        menuCriarUsuario = new javax.swing.JMenuItem();
        menuCriarAtendente = new javax.swing.JMenuItem();
        menuMeuPerfil = new javax.swing.JMenuItem();
        menuListarUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuLogout = new javax.swing.JMenuItem();
        menuEquipe = new javax.swing.JMenu();
        menuCriarEquipe = new javax.swing.JMenuItem();
        menuEquipes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clio Helpdesk");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelInfo.add(lblInfo);

        getContentPane().add(panelInfo, java.awt.BorderLayout.PAGE_START);

        painelPrincipal.setLayout(new java.awt.CardLayout());
        getContentPane().add(painelPrincipal, java.awt.BorderLayout.CENTER);

        menuChamdos.setText("Chamados");
        menuChamdos.setActionCommand("");
        menuChamdos.setEnabled(false);

        menuCriarChamado.setText("Criar Chamado");
        menuCriarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCriarChamadoActionPerformed(evt);
            }
        });
        menuChamdos.add(menuCriarChamado);

        menuMeusChamados.setText("Meus Chamados");
        menuMeusChamados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMeusChamadosActionPerformed(evt);
            }
        });
        menuChamdos.add(menuMeusChamados);

        menuChamadoSemAtendentes.setText("Atender Chamado");
        menuChamadoSemAtendentes.setEnabled(false);
        menuChamadoSemAtendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChamadoSemAtendentesActionPerformed(evt);
            }
        });
        menuChamdos.add(menuChamadoSemAtendentes);

        menuChamadoTodos.setText("Todos os Chamados");
        menuChamadoTodos.setEnabled(false);
        menuChamadoTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuChamadoTodosActionPerformed(evt);
            }
        });
        menuChamdos.add(menuChamadoTodos);

        jMenuBar1.add(menuChamdos);

        menuUsuario.setText("Usuário");
        menuUsuario.setEnabled(false);

        menuCriarUsuario.setText("Criar Usuario");
        menuCriarUsuario.setEnabled(false);
        menuCriarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCriarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuCriarUsuario);

        menuCriarAtendente.setText("Criar Atendente");
        menuCriarAtendente.setToolTipText("");
        menuCriarAtendente.setEnabled(false);
        menuCriarAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCriarAtendenteActionPerformed(evt);
            }
        });
        menuUsuario.add(menuCriarAtendente);

        menuMeuPerfil.setText("Meu Perfil");
        menuMeuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMeuPerfilActionPerformed(evt);
            }
        });
        menuUsuario.add(menuMeuPerfil);

        menuListarUsuario.setText("Listar Usuario");
        menuListarUsuario.setEnabled(false);
        menuListarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarUsuarioActionPerformed(evt);
            }
        });
        menuUsuario.add(menuListarUsuario);
        menuUsuario.add(jSeparator1);

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuUsuario.add(menuLogout);

        jMenuBar1.add(menuUsuario);

        menuEquipe.setText("Equipe");
        menuEquipe.setEnabled(false);

        menuCriarEquipe.setText("Criar Equipe");
        menuCriarEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCriarEquipeActionPerformed(evt);
            }
        });
        menuEquipe.add(menuCriarEquipe);

        menuEquipes.setText("Listar Equipes");
        menuEquipes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEquipesActionPerformed(evt);
            }
        });
        menuEquipe.add(menuEquipes);

        jMenuBar1.add(menuEquipe);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMeuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMeuPerfilActionPerformed
        painelUsuario.setUsuario(usuarioLogado);
        showPainel(PAINEL_USUARIO);
    }//GEN-LAST:event_menuMeuPerfilActionPerformed

    private void menuCriarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCriarChamadoActionPerformed
        painelChamado.setChamado(CHAMADO_CONTROLLER.novoChamado(usuarioLogado));
        showPainel(PAINEL_CHAMADO);
    }//GEN-LAST:event_menuCriarChamadoActionPerformed

    private void menuCriarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCriarUsuarioActionPerformed
        painelUsuario.setUsuario(USUARIO_CONTROLLER.novoUsuario());
        showPainel(PAINEL_USUARIO);
    }//GEN-LAST:event_menuCriarUsuarioActionPerformed

    private void menuCriarEquipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCriarEquipeActionPerformed
        painelEquipe.setEquipe(EQUIPE_CONTROLLER.novoEquipe());
        showPainel(PAINEL_EQUIPE);
    }//GEN-LAST:event_menuCriarEquipeActionPerformed

    private void menuMeusChamadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMeusChamadosActionPerformed
        painelChamados.setChamados(CHAMADO_CONTROLLER.getChamadosBySolicitante(usuarioLogado));
        showPainel(PAINEL_CHAMADOS);
    }//GEN-LAST:event_menuMeusChamadosActionPerformed

    private void menuChamadoSemAtendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChamadoSemAtendentesActionPerformed
        painelChamados.setChamados(CHAMADO_CONTROLLER.getChamadosNaoAtendidos());
        showPainel(PAINEL_CHAMADOS);
    }//GEN-LAST:event_menuChamadoSemAtendentesActionPerformed

    private void menuListarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarUsuarioActionPerformed
        painelUsuarios.setUsuarios(USUARIO_CONTROLLER.getAllUsuarios());
        showPainel(PAINEL_USUARIOS);
    }//GEN-LAST:event_menuListarUsuarioActionPerformed

    private void menuEquipesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEquipesActionPerformed
        painelEquipes.setEquipes(EQUIPE_CONTROLLER.getAllEquipe());
        showPainel(PAINEL_EQUIPES);
    }//GEN-LAST:event_menuEquipesActionPerformed

    private void menuCriarAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCriarAtendenteActionPerformed
        painelUsuario.setUsuario(USUARIO_CONTROLLER.novoAtendente());
        showPainel(PAINEL_USUARIO);
    }//GEN-LAST:event_menuCriarAtendenteActionPerformed

    private void menuChamadoTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuChamadoTodosActionPerformed
        painelChamados.setChamados(CHAMADO_CONTROLLER.getAllChamado());
        showPainel(PAINEL_CHAMADOS);
    }//GEN-LAST:event_menuChamadoTodosActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        usuarioLogado = USUARIO_CONTROLLER.novoUsuario();
        showPainel(PAINEL_LOGIN);
        menuChamdos.setEnabled(false);
        menuUsuario.setEnabled(false);
        menuEquipe.setEnabled(false);
        menuCriarUsuario.setEnabled(false);
        menuCriarAtendente.setEnabled(false);
        menuListarUsuario.setEnabled(false);
        menuChamadoSemAtendentes.setEnabled(false);
        menuChamadoTodos.setEnabled(false);
    }//GEN-LAST:event_menuLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Equipe eTeste = new Equipe();
                eTeste.setNome("teste");
                Atendente aTeste =  new Atendente();
                aTeste.setNome("atendente");
                aTeste.setSenha("senha");
                try {
                    aTeste.criptografaSenha();
                } catch (UnsupportedEncodingException ex) {
                }
                aTeste.setEmail("atendente");
                EQUIPE_CONTROLLER.saveEquipe(eTeste);
                USUARIO_CONTROLLER.saveUsuario(aTeste);
                TelaPrincipal.getInstance().expiraCamado();
                TelaPrincipal.getInstance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JMenuItem menuChamadoSemAtendentes;
    private javax.swing.JMenuItem menuChamadoTodos;
    private javax.swing.JMenu menuChamdos;
    private javax.swing.JMenuItem menuCriarAtendente;
    private javax.swing.JMenuItem menuCriarChamado;
    private javax.swing.JMenuItem menuCriarEquipe;
    private javax.swing.JMenuItem menuCriarUsuario;
    private javax.swing.JMenu menuEquipe;
    private javax.swing.JMenuItem menuEquipes;
    private javax.swing.JMenuItem menuListarUsuario;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuMeuPerfil;
    private javax.swing.JMenuItem menuMeusChamados;
    private javax.swing.JMenu menuUsuario;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel panelInfo;
    // End of variables declaration//GEN-END:variables
}
