/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import java.util.List;
import model.Usuario;

/**
 *
 * @author Pichau
 */
public class UsuariosView extends javax.swing.JPanel {
    private static final UsuarioController USUARIO_CONTROLLER = UsuarioController.getInstance();
    private static UsuariosView instance;

    public static UsuariosView getInstance(List<Usuario> usuarios) {
        if(instance==null){
            instance = new UsuariosView(usuarios);
        }
        return instance;
    }
    
    private UsuariosTableModel usuariosTableModel;
    
    public UsuariosView(List<Usuario> usuarios) {
        this.usuariosTableModel = new UsuariosTableModel(usuarios);
        initComponents();
    }
    
    public void setUsuarios(List<Usuario> usuarios){
        UsuariosTableModel atualiza = new UsuariosTableModel(usuarios);
        tableUsuarios.setModel(atualiza);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtPesquisaEmail = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsuarios = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        txtPesquisaEmail.setColumns(20);
        txtPesquisaEmail.setToolTipText("e-mail do usuario");
        jPanel2.add(txtPesquisaEmail);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(btnPesquisar);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        tableUsuarios.setModel(this.usuariosTableModel);
        tableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableUsuarios);

        jPanel1.add(jScrollPane1);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableUsuariosMouseClicked
        if(evt.getClickCount()==2){
            int selectedRow = tableUsuarios.getSelectedRow();
            UsuariosTableModel model = (UsuariosTableModel) tableUsuarios.getModel();
            Usuario usuarioByIndex = model.getUsuarioByIndex(selectedRow);
            UsuarioView.getInstance().setUsuario(usuarioByIndex);
            TelaPrincipal.getInstance().showPainel(TelaPrincipal.PAINEL_USUARIO);
        }
    }//GEN-LAST:event_tableUsuariosMouseClicked

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        USUARIO_CONTROLLER.getUsuariosByEmail(txtPesquisaEmail.getText());
    }//GEN-LAST:event_btnPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUsuarios;
    private javax.swing.JTextField txtPesquisaEmail;
    // End of variables declaration//GEN-END:variables
}
